import Link from 'next/link';
import Script from 'next/script';
import { notFound } from 'next/navigation';
import PageHero from '@/components/PageHero';
import { projects } from '@/lib/siteData';
import { pageMetadata } from '@/lib/seo';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);return p?pageMetadata(p.title,p.summary,`/projects/${p.slug}`):{};}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);if(!p)notFound();const related=projects.filter(x=>x.category===p.category&&x.slug!==p.slug).slice(0,3);const schema={'@context':'https://schema.org','@type':'CreativeWork',name:p.title,description:p.summary,image:p.image,about:p.category};return <><PageHero title={p.title} eyebrow={p.category} path={`/projects/${p.slug}`} image={p.image} parent={{label:'Recent Projects',href:'/about/recent-projects'}}/><section className="section"><div className="shell project-detail"><div><div className="project-detail-image" style={{backgroundImage:`url("${p.image}")`}} role="img" aria-label={p.title}/></div><div className="project-detail-copy"><div className="project-meta">{p.category}<span>•</span>{p.location}</div><h2>Project Overview</h2><p>{p.summary}</p><div className="project-actions"><a className="button primary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.title+' '+p.location)}`}>Open in Maps ↗</a><Link className="button outline" href="/contact">Discuss a Project</Link></div></div></div></section><section className="section related-section"><div className="shell"><h2>Related {p.category} Projects</h2><div className="highlight-grid">{related.map(r=><Link key={r.slug} className="highlight-card" href={`/projects/${r.slug}`} style={{backgroundImage:`linear-gradient(180deg,transparent 40%,rgba(8,29,35,.88)),url("${r.image}")`}}><h3>{r.title}</h3><small>{r.location}</small></Link>)}</div></div></section><Script id={`project-schema-${p.slug}`} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
