import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import PageHero from '@/components/PageHero';
import { projects, services } from '@/lib/siteData';
import { pageMetadata } from '@/lib/seo';
export function generateStaticParams(){return services.map(s=>({slug:s.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(x=>x.slug===slug);return s?pageMetadata(s.title,s.intro,`/our-services/${s.slug}`):{};}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const s=services.find(x=>x.slug===slug); if(!s)notFound(); const highlights=s.highlights.map(t=>projects.find(p=>p.title===t)).filter(Boolean);return <><PageHero title={s.title} path={`/our-services/${s.slug}`} parent={{label:'Services',href:'/our-services'}} image={s.image}/><section className="section"><div className="shell service-detail"><div className="service-copy"><p className="lead">{s.intro}</p>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}<h2>Services include</h2><ul className="service-bullets">{s.bullets.map(x=><li key={x}>{x}</li>)}</ul></div><aside className="service-aside"><Image src={s.image} alt={`${s.title} engineering services`} width={900} height={675} sizes="(max-width: 940px) 100vw, 330px" /><div className="service-contact"><h3>Talk with Odyssey</h3><p>Discuss a project with the team.</p><Link href="/contact">Contact Us →</Link></div></aside></div></section>{highlights.length>0&&<section className="section highlights-section"><div className="shell"><div className="section-title-line"><h2>Project Highlights</h2><Link href="/about/recent-projects">All projects</Link></div><div className="highlight-grid">{highlights.map(p=>p&&<Link key={p.slug} className="highlight-card" href={`/projects/${p.slug}`} style={{backgroundImage:`linear-gradient(180deg,transparent 40%,rgba(8,29,35,.88)),url("${p.image}")`}}><span>{p.category}</span><h3>{p.title}</h3></Link>)}</div></div></section>}</>}
