import Link from 'next/link';
import PageHero from '@/components/PageHero';
import { pageMetadata } from '@/lib/seo';
export const metadata = pageMetadata('About Odyssey Engineering Group','Learn about Odyssey Engineering Group, its founders and core philosophies.','/about');
export default function AboutPage(){return <>
  <PageHero title="About Odyssey Engineering Group" path="/about" description="A Houston civil engineering firm built around integrity, teamwork, communication and community involvement." image="https://www.odysseyeg.com/wp-content/uploads/2024/05/oeg_home_about_1.jpg"/>
  <section className="section"><div className="shell content-two-col"><div className="prose-lg"><p>Founded in 2016 by Justin R. Ring, P.E. and Megan L. Crutcher, P.E., CFM, Odyssey Engineering Group was created with the idea that an engineering firm should participate in the communities it helps build—not simply deliver plans.</p><p>That philosophy has shaped the firm’s growth, client relationships and internal culture. Odyssey has expanded into an integrated team serving land development, municipal, stormwater, site, GIS and survey needs across the Greater Houston region.</p><p>The firm’s four core philosophies—Integrity Driven, Team Centered, Communication Focused and Pay It Forward—remain the framework for how the company approaches clients, employees and civic involvement.</p></div><aside className="about-side"><h2>Explore Odyssey</h2><Link href="/about/management-team">Management Team <span>→</span></Link><Link href="/about/recent-projects">Recent Projects <span>→</span></Link><Link href="/outreach">Odyssey Outreach <span>→</span></Link></aside></div></section>
  <section className="section philosophy-section"><div className="shell philosophy-grid"><article><h2>Integrity Driven</h2><p>Trust starts with direct, honest professional judgment and dependable follow-through.</p></article><article><h2>Team Centered</h2><p>Projects move forward when people collaborate, communicate openly and work toward the same outcome.</p></article><article><h2>Communication Focused</h2><p>Responsive communication helps prevent avoidable delays and keeps clients informed.</p></article><article><h2>Pay It Forward</h2><p>Odyssey encourages community service, mentorship and participation in organizations that strengthen the region.</p></article></div></section>
</>}
